### PR TITLE
Clean up and fix port forwarding example.

### LINKED ISSUE #297: Port Forward example not working
I am using Port forward example where I need to forward the port of running service. I have service running inside pod on port 3122. 
When I redirect it to 8080. The url is localhost:8080 and has UI but I don't see full UI. Only I can see the service name mentioned in Title bar of browser.

Debug:
```
if (bytesRec == 0 || Encoding.ASCII.GetString(bytes,0,bytesRec).IndexOf("<EOF>") > -1) {  
                            break;  
}
```
Coming always false `Encoding.ASCII.GetString(bytes,0,bytesRec).IndexOf("<EOF>") > -1`

But if I execute same using kubectl command then it works perfectly fine. 
`kubectl port-forward service/dbdashboard 8080:3122 -n my_namespace`

**Note:** k8s cluster is not installed on my system. I am using k8s cluster which is installed on Azure cloud.

### PR DESCRIPTION
**Pull request by brendandburns**
Fixes #297

### CODE REVIEW

File: examples/portforward/PortForward.cs [hunk 1]
```diff
@@ -61,6 +62,10 @@ private static async Task Main(string[] args)
 
             await accept;
             await copy;
+            if (handler != null) {
```
Comment (tg123) [inline examples/portforward/PortForward.cs]: handler?.Close()

Comment (tg123) [inline examples/portforward/PortForward.cs]:
```suggestion
            handler?.Close();            
```

**Comment by tg123** [comment]
/LGTM 
with some suggestion
