### PR TITLE
fix: Exec hangs

### LINKED ISSUE #1266: Expose exec Standard error
**Describe the bug**
When connecting to a new Azure AKS instance, kubelogin exposes a URL that we must open. I think we have to somehow expose this in the client so the user can interact with the URL as needed. Kubelogin exposes this output as Standard Error.
image

**Kubernetes C# SDK Client Version**
10.1.19

**Server Kubernetes Version**
1.25.4

**Dotnet Runtime Version**
net6

**To Reproduce**
Install Azure CLI

az aks get-credentials --resource-group $ResourceGroup --name $Name --subscription $Subscription 

Load Kubeconfig with the client and attempt to list Pods etc.

**Expected behavior**
Client should expose standard error for exec and keep the process open and allow us view the output.

**Where do you run your app with Kubernetes SDK (please complete the following information):**
 - OS: Windows
 - Cloud: Azure

### PR DESCRIPTION
**Pull request by IvanJosipovic**
Fixes #1266

### CODE REVIEW

File: src/KubernetesClient/KubernetesClientConfiguration.ConfigFile.cs [hunk 1]
```diff
@@ -557,13 +558,38 @@ public static ExecCredentialResponse ExecuteExternalCommand(ExternalExecution co
...
-            var stdout = process.StandardOutput.ReadToEnd();
-            var stderr = process.StandardError.ReadToEnd();
-            if (string.IsNullOrWhiteSpace(stderr) == false)
+            var sb = new StringBuilder();
+            var buffer = new char[1024];
+            while (true)
+            {
+                var readTask = process.StandardError.ReadAsync(buffer, 0, buffer.Length);
+
+                if (readTask.Wait(TimeSpan.FromSeconds(2)))
```
Comment (tg123) [inline src/KubernetesClient/KubernetesClientConfiguration.ConfigFile.cs:567]: exec will still hang if the process is consistently sending output, right?

File: src/KubernetesClient/KubernetesClientConfiguration.ConfigFile.cs [hunk 2]
```diff
@@ -557,13 +558,38 @@ public static ExecCredentialResponse ExecuteExternalCommand(ExternalExecution co
...
+
+            if (!string.IsNullOrWhiteSpace(stderr))
             {
                 throw new KubeConfigException($"external exec failed due to: {stderr}");
             }
 
+            var stdout = process.StandardOutput.ReadToEnd();
+
             // Wait for a maximum of 5 seconds, if a response takes longer probably something went wrong...
             process.WaitForExit(5);
```
Comment (tg123) [inline src/KubernetesClient/KubernetesClientConfiguration.ConfigFile.cs:594]: maybe it is to move wait output to a task and put a overall timeout here

File: src/KubernetesClient/KubernetesClientConfiguration.ConfigFile.cs (hunk 1 above)
Comment (IvanJosipovic) [reply src/KubernetesClient/KubernetesClientConfiguration.ConfigFile.cs:567]: That is correct, if the external application keeps sending errors. This will continue looping until it stops for two seconds.

My only experience has been with Kubelogin. I'm not sure how other clients behave here.

Comment (tg123) [reply src/KubernetesClient/KubernetesClientConfiguration.ConfigFile.cs:567]: link #1092

File: src/KubernetesClient/KubernetesClientConfiguration.ConfigFile.cs (hunk 2 above)
Comment (IvanJosipovic) [reply src/KubernetesClient/KubernetesClientConfiguration.ConfigFile.cs]: I added a 5s timeout to the StandardOutput.

File: src/KubernetesClient/KubernetesClientConfiguration.ConfigFile.cs (hunk 1 above)
Comment (IvanJosipovic) [reply src/KubernetesClient/KubernetesClientConfiguration.ConfigFile.cs]: @tg123, thanks for linking that issue. I used the Event based option from that Issue and updated the PR.

Now, the process will timeout after 5 seconds no matter what, then we check if stderror has a value, if it does we will throw the response as an exception otherwise we throw a timeout exception.

The only gap remaining is the process will stick around on Errors indefinitely. We might need to add some more code to store the processes and kill them after 5 minutes or something. Let me know if you want me to code this in.

File: src/KubernetesClient/KubernetesClientConfiguration.ConfigFile.cs [hunk 3]
```diff
@@ -548,24 +548,33 @@ public static ExecCredentialResponse ExecuteExternalCommand(ExternalExecution co
...
             catch (Exception ex)
             {
                 throw new KubeConfigException($"external exec failed due to: {ex.Message}");
             }
 
-            var stdout = process.StandardOutput.ReadToEnd();
-            var stderr = process.StandardError.ReadToEnd();
-            if (string.IsNullOrWhiteSpace(stderr) == false)
+            // Wait for a maximum of 5 seconds, if a response takes longer probably something went wrong...
+            if (!process.WaitForExit(5000) && string.IsNullOrWhiteSpace(stderr))
```
Comment (brendandburns) [inline src/KubernetesClient/KubernetesClientConfiguration.ConfigFile.cs:569]: We should perhaps wait even longer if the terminal is interactive. Something like this:

https://stackoverflow.com/questions/45393001/determine-if-net-core-console-application-is-running-in-user-interactive-mode

It feels like 5s is pretty fast to get to a web browser and get logged in.

**Comment by brendandburns** [comment]
This looks reasonable to me. Thanks for the PR!

File: src/KubernetesClient/KubernetesClientConfiguration.ConfigFile.cs (hunk 3 above)
Comment (IvanJosipovic) [reply src/KubernetesClient/KubernetesClientConfiguration.ConfigFile.cs:569]: When Kubelogin asks for an interactive prompt, it will return an error. However, the process will not be killed.

**Comment by IvanJosipovic** [comment]
I'm not sure why this test (k8s.Tests.AuthTests.ExternalToken) is failing, its working locally for me.

image

File: src/KubernetesClient/KubernetesClientConfiguration.ConfigFile.cs [hunk 4]
```diff
@@ -557,19 +558,51 @@ public static ExecCredentialResponse ExecuteExternalCommand(ExternalExecution co
...
+            var stderrBuilder = new StringBuilder();
+
+            var stdOutTask = process.StandardOutput.ReadToEndAsync(); // Assumes process exits
+
+            var buffer = new char[1024];
+
+            var stopwatch = Stopwatch.StartNew();
+
+            // Wait for a maximum of 5 seconds, if a response takes longer probably something went wrong...
+            while (!stdOutTask.IsCompleted && stopwatch.Elapsed < TimeSpan.FromSeconds(5))
```
Comment (tg123) [inline src/KubernetesClient/KubernetesClientConfiguration.ConfigFile.cs:570]: you can do the pattern like below without have to loop and sleep, which will always cause thread to sleep 500ms

```
t = task.create { readstdout and stderr }
task.waitany(delay(timeout), t)
```

Comment (tg123) [inline src/KubernetesClient/KubernetesClientConfiguration.ConfigFile.cs:570]: could you please move timeout to config

Comment (IvanJosipovic) [reply src/KubernetesClient/KubernetesClientConfiguration.ConfigFile.cs:570]: I tried that logic last night, however, it introduced another issue and it still needed a loop. Let me bring it back and see if I might have missed something as it was rater late.

Comment (tg123) [reply src/KubernetesClient/KubernetesClientConfiguration.ConfigFile.cs:570]: add ct to readasync

Comment (IvanJosipovic) [reply src/KubernetesClient/KubernetesClientConfiguration.ConfigFile.cs]: @tg123, any suggestion where to place it?

File: src/KubernetesClient/KubernetesClientConfiguration.ConfigFile.cs [hunk 5]
```diff
@@ -557,19 +558,32 @@ public static ExecCredentialResponse ExecuteExternalCommand(ExternalExecution co
...
+                if (stderrBuilder.Length > 0)
+                {
+                    throw new KubeConfigException($"external exec failed due to: {stderrBuilder}");
+                }
+            }
 
             try
             {
-                var responseObject = KubernetesJson.Deserialize<ExecCredentialResponse>(stdout);
+                var responseObject = KubernetesJson.Deserialize<ExecCredentialResponse>(stdOutTask.Result);
```
Comment (tg123) [inline src/KubernetesClient/KubernetesClientConfiguration.ConfigFile.cs:586]: `.Result` vs `getawait()`

see https://stackoverflow.com/questions/17284517/is-task-result-the-same-as-getawaiter-getresult

for better explanation

File: src/KubernetesClient/KubernetesClientConfiguration.ConfigFile.cs [hunk 6]
```diff
@@ -557,19 +558,32 @@ public static ExecCredentialResponse ExecuteExternalCommand(ExternalExecution co
...
+                throw new KubeConfigException("external exec failed due to timeout");
             }
+            else if (result == 0)
+            {
+                var stderrBuilder = new StringBuilder();
+                stderrBuilder.Append(buffer, 0, stdErrorTask.Result);
 
-            // Wait for a maximum of 5 seconds, if a response takes longer probably something went wrong...
-            process.WaitForExit(5);
+                if (stderrBuilder.Length > 0)
```
Comment (tg123) [inline src/KubernetesClient/KubernetesClientConfiguration.ConfigFile.cs:578]: here my suggestion is to ignore stderr
throw only when cannot deserialize the stdout

the exec may write some debug log to stderr

File: src/KubernetesClient/KubernetesClientConfiguration.ConfigFile.cs [hunk 7]
```diff
@@ -557,19 +558,32 @@ public static ExecCredentialResponse ExecuteExternalCommand(ExternalExecution co
...
-            var stdout = process.StandardOutput.ReadToEnd();
-            var stderr = process.StandardError.ReadToEnd();
-            if (string.IsNullOrWhiteSpace(stderr) == false)
+
+            var stdOutTask = process.StandardOutput.ReadToEndAsync(); // Assumes process exits
+
+            var buffer = new char[4096];
+            var stdErrorTask = process.StandardError.ReadAsync(buffer, 0, buffer.Length); // Assumes process will continue
+
+            var result = Task.WaitAny(new Task[] { stdErrorTask, stdOutTask }, TimeSpan.FromSeconds(10));
```
Comment (tg123) [inline src/KubernetesClient/KubernetesClientConfiguration.ConfigFile.cs:567]: 10 sec to config?

Comment (tg123) [reply src/KubernetesClient/KubernetesClientConfiguration.ConfigFile.cs:567]: what about `KubernetesClientConfiguration`

Comment (IvanJosipovic) [reply src/KubernetesClient/KubernetesClientConfiguration.ConfigFile.cs]: I added a static property to KubernetesClientConfiguration.

File: src/KubernetesClient/KubernetesClientConfiguration.ConfigFile.cs [hunk 8]
```diff
@@ -28,6 +29,11 @@ public partial class KubernetesClientConfiguration
         // For testing
         internal static string KubeConfigEnvironmentVariable { get; set; } = "KUBECONFIG";
 
+        /// <summary>
+        /// Exec process timeout in seconds
+        /// </summary>
+        public static int ExecTimeout { get; set; } = 10;
```
Comment (tg123) [inline src/KubernetesClient/KubernetesClientConfiguration.ConfigFile.cs:35]: any reason why this is not per inst var?

Comment (IvanJosipovic) [reply src/KubernetesClient/KubernetesClientConfiguration.ConfigFile.cs:35]: @tg123 currently the ExecuteExternalCommand command which uses it is Static.

File: src/KubernetesClient/KubernetesClientConfiguration.ConfigFile.cs (hunk 6 above)
Comment (IvanJosipovic) [reply src/KubernetesClient/KubernetesClientConfiguration.ConfigFile.cs:582]: I think logging of non errors to stderr is a bad practice.

My testing of kubelogin shows the following workflow, and I modeled the current logic to follow.

kubelogin drawio


Also looking at the google auth plugin appears to be similar, errors are only printed on error conditions.
https://github.com/kubernetes/cloud-provider-gcp/blob/master/cmd/gke-gcloud-auth-plugin/cred.go#L145

File: src/KubernetesClient/KubernetesClientConfiguration.ConfigFile.cs (hunk 8 above)
Comment (tg123) [reply src/KubernetesClient/KubernetesClientConfiguration.ConfigFile.cs:35]: oh i see, what about make ExecuteExternalCommand non static?
it is weird to this value static

Comment (IvanJosipovic) [reply src/KubernetesClient/KubernetesClientConfiguration.ConfigFile.cs:35]: Its static as its used outside here, https://github.com/kubernetes-client/csharp/blob/e42290d6f7c7fbb515cca119e8c3f7507bd00ce2/src/KubernetesClient/Authentication/ExecTokenProvider.cs#L46

File: src/KubernetesClient/KubernetesClientConfiguration.ConfigFile.cs (hunk 6 above)
Comment (tg123) [reply src/KubernetesClient/KubernetesClientConfiguration.ConfigFile.cs:582]: just double checked client-go

https://github.com/kubernetes/client-go/blob/6c514ab3ffc5f500fd373f09956780c0e3bbe028/plugin/pkg/client/auth/exec/exec.go#L450

the impl is to ignore and redirect stderr to os.stderr and deserialize the stdout directly

File: src/KubernetesClient/KubernetesClientConfiguration.ConfigFile.cs (hunk 8 above)
Comment (tg123) [reply src/KubernetesClient/KubernetesClientConfiguration.ConfigFile.cs:35]: oh i see, that is difficult to change, lets keep it `static`

ps i do not think anyone is going to modify it

File: src/KubernetesClient/KubernetesClientConfiguration.ConfigFile.cs (hunk 6 above)
Comment (IvanJosipovic) [reply src/KubernetesClient/KubernetesClientConfiguration.ConfigFile.cs:582]: I'm not sure how to ignore the stderr as we need its data, and also block the call and wait for stdout. The current model works well with my testing.
See recording [Video.webm](https://user-images.githubusercontent.com/9521987/234685591-bc3a70de-0099-4355-bb9c-547c022ca3bb.webm)

Any suggestions?

Comment (tg123) [reply src/KubernetesClient/KubernetesClientConfiguration.ConfigFile.cs:582]: ignore here means do not `if (stderrBuilder.Length > 0)`
just leave it there, only throw it if  cannot deserialize stdout

BTW this kubeui is so cool

**Comment by IvanJosipovic** [comment]
I think this approach closely resembles the Go client.

File: src/KubernetesClient/KubernetesClientConfiguration.ConfigFile.cs [hunk 9]
```diff
@@ -551,25 +561,25 @@ public static ExecCredentialResponse ExecuteExternalCommand(ExternalExecution co
...
-                throw new KubeConfigException($"external exec failed due to: {stderr}");
-            }
-
-            // Wait for a maximum of 5 seconds, if a response takes longer probably something went wrong...
-            process.WaitForExit(5);
-
             try
             {
-                var responseObject = KubernetesJson.Deserialize<ExecCredentialResponse>(stdout);
+                if (!process.WaitForExit((int)TimeSpan.FromSeconds(ExecTimeout).TotalMilliseconds))
```
Comment (tg123) [inline src/KubernetesClient/KubernetesClientConfiguration.ConfigFile.cs:577]:
```suggestion
                if (!process.WaitForExit(TimeSpan.FromSeconds(ExecTimeout))
```

File: src/KubernetesClient/KubernetesClientConfiguration.ConfigFile.cs [hunk 10]
```diff
@@ -28,6 +28,16 @@ public partial class KubernetesClientConfiguration
         // For testing
         internal static string KubeConfigEnvironmentVariable { get; set; } = "KUBECONFIG";
 
+        /// <summary>
+        ///     Exec process timeout in seconds
+        /// </summary>
+        public static int ExecTimeout { get; set; } = 120;
```
Comment (tg123) [inline src/KubernetesClient/KubernetesClientConfiguration.ConfigFile.cs:34]: or make timespan here

**Review by tg123 — COMMENTED** [review]
suggest use timespan instead of second 
then LGTM

**Review by tg123 — APPROVED** [review]
/LGTM
